// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAglR-hd5jIzZx3NWToWOP-n9J3ESEuOLM',
    appId: '1:597044733093:web:d5a6485d79d937c019594c',
    messagingSenderId: '597044733093',
    projectId: 'luarsekolah-ea54e',
    authDomain: 'luarsekolah-ea54e.firebaseapp.com',
    storageBucket: 'luarsekolah-ea54e.firebasestorage.app',
    measurementId: 'G-Q0J8Q4JHQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE6x4NWnSHi0CsCXb6nV6XEduxBSJvtkc',
    appId: '1:597044733093:android:ad57259780dd85b719594c',
    messagingSenderId: '597044733093',
    projectId: 'luarsekolah-ea54e',
    storageBucket: 'luarsekolah-ea54e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDj4DEZQUXCvVAXUQDCxZn2IOSaq3EAto',
    appId: '1:597044733093:ios:c2431c2fd8459d7819594c',
    messagingSenderId: '597044733093',
    projectId: 'luarsekolah-ea54e',
    storageBucket: 'luarsekolah-ea54e.firebasestorage.app',
    iosBundleId: 'com.example.luarsekolah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDj4DEZQUXCvVAXUQDCxZn2IOSaq3EAto',
    appId: '1:597044733093:ios:c2431c2fd8459d7819594c',
    messagingSenderId: '597044733093',
    projectId: 'luarsekolah-ea54e',
    storageBucket: 'luarsekolah-ea54e.firebasestorage.app',
    iosBundleId: 'com.example.luarsekolah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAglR-hd5jIzZx3NWToWOP-n9J3ESEuOLM',
    appId: '1:597044733093:web:297366c4d95e17a319594c',
    messagingSenderId: '597044733093',
    projectId: 'luarsekolah-ea54e',
    authDomain: 'luarsekolah-ea54e.firebaseapp.com',
    storageBucket: 'luarsekolah-ea54e.firebasestorage.app',
    measurementId: 'G-W74CZF0ZZM',
  );
}
